version: '3.1'

services:
   
    web-server:
        image: webdev89/phpdebian
        container_name: appHare 
        ports:
          - 8647:80
        environment:
          DB_HOST: db
          DB_DB: hare
          DB_USER: user
          DB_PASS: user
        volumes:
            - ./dist/:/var/www/html
        depends_on:
          - db
        networks:
          - hare
          
    db:
        image: mysql:5.7
        container_name: HareMysql
        restart: always
        ports:
          - 8646:3306
        environment:
          MYSQL_DATABASE: hare
          MYSQL_USER: user 
          MYSQL_PASSWORD: user
          MYSQL_ROOT_PASSWORD: root
        volumes:
          - ./dump:/docker-entrypoint-initdb.d
          - MysqlHare2:/var/lib/mysql
        networks:
          - hare

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_hare
        restart: always
        ports: 
          - 8629:80
        environment:
          PMA_HOST: db
        depends_on:
          - db
        networks:
          - hare
          
networks:
  hare:
    driver: bridge

volumes:
  MysqlHare2:
